# Generated by Django 5.2.6 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('photocard', 'Photocard'), ('jersey', 'Jersey Card'), ('event', 'Event Card'), ('sponsorship', 'Sponsorship'), ('pack', 'Booster Pack')], max_length=31),
        ),
    ]
