# Generated by Django 5.2.6 on 2025-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('photocard', 'Photocard'), ('gear', 'Gear Card'), ('jersey', 'Jersey Card'), ('event', 'Event Card'), ('sponsorship', 'Sponsorship'), ('pack', 'Booster Pack')], max_length=31),
        ),
    ]
